### ISSUE TITLE
TooManyRegister

### ISSUE THREAD

**Issue by ignoracenfly** [Kovirum/hamster_kombat_bike_keygen_web#1]
{"error_code":"TooManyRegister","error_message":"Register event timeout"}
已经被限制了吗

**Comment by Kovirum** [comment]
Hello. Can you clarify the essence of your problem, the steps that led to its occurrence and additional information that will help to understand your request.

**Comment by ignoracenfly** [comment]
您的邮件已经收到。谢谢

**Comment by Kovirum** [comment]
This console error is part of the algorithm's operation and does not have a negative impact on the operation of the generator, so no action will be taken at the moment.
