### ISSUE TITLE
TwerkRace key generation problem

### ISSUE THREAD

**Issue by skaterfat** [Kovirum/hamster_kombat_bike_keygen_web#13]
I think this is because two variables (appToken and promoId) has same values

**Comment by Kovirum** [comment]
Could you describe in more detail the problem you face when generating code? my tests have shown that the keys are generated correctly

**Comment by Kovirum** [comment]
So, I have not received any explanations, and there have been no complaints about this game. By the way, the same values of variables don't mean anything at all. **Closed.**
