### ISSUE TITLE
My Clone Army Generation Issue

### ISSUE THREAD

**Issue by MohammadHk8** [Kovirum/hamster_kombat_bike_keygen_web#14]
Clone generator does not work.
No errors no nothing you just don't get any codes.
![Clone](https://github.com/user-attachments/assets/0953320b-0c21-45f6-ab05-7a0909e1b2a9)

**Comment by Lightbass** [comment]
I have same issue too.
Response body from service:
{"error_code":"TooManyRegister","error_message":"Register event timeout"}
https://api.gamepromo.io/promo/register-event
POST 400 

Somehow service detecting generator or algorithm for get keys changed.
I try VPN and private mode in browser, get same result

**Comment by MohammadHk8** [comment]
![image](https://github.com/user-attachments/assets/1700d6f8-5728-4574-864c-c08a2acb6bb9)

**Comment by Kovirum** [comment]
This problem is definitely not related to the detection of the generator and is most likely the above error. I have an assumption that this game now requires more attempts to get the key. I'm going to run some tests now and if I'm right, it will be very easy to fix it, but unfortunately the time to get the key will increase.

**Comment by Lightbass** [comment]
Yeah, with const EVENTS_DELAY = 120000 generator seems successfully work.
With 60000 get error.
Maybe here is optimal value between 1 and 2 minutes

**Comment by Kovirum** [comment]
Yes, that's right, **EVENTS_DELAY** had a direct impact on performance. So far, I'm testing the value of `70000`, at which the generator seems to be working stably. I will change the config so that it is possible to configure **EVENTS_DELAY** for each game individually and make a commit as soon as I select the best value for **MyCloneArmy**.

**Comment by EVMlord** [comment]
```

const gamePromoConfigs = {
  MyCloneArmy: {
    appToken: "74ee0b5b-775e-4bee-974f-63e7f4d5bacb",
    promoId: "fe693b26-b342-4159-8808-15e3ff7f8767",
    eventsDelay: 70000, // Set the EVENTS_DELAY for MyCloneArmy
  },
  ChainCube2048: {
    appToken: "d1690a07-3780-4068-810f-9b5bbf2931b2",
    promoId: "b4170868-cef0-424f-8eb9-be0622e8e8e3",
    eventsDelay: 25000, // Set the EVENTS_DELAY for ChainCube2048
  },
  TrainMiner: {
    appToken: "82647f43-3f87-402d-88dd-09a90025313f",
    promoId: "c4480ac7-e178-4973-8061-9ed5b2e17954",
    eventsDelay: 18000, // Set the EVENTS_DELAY for TrainMiner
  },
  BikeRide3D: {
    appToken: "d28721be-fd2d-4b45-869e-9f253b554e50",
    promoId: "43e35910-c168-4634-ad4f-52fd764a843f",
    eventsDelay: 22000, // Set the EVENTS_DELAY for BikeRide3D
  },
  MergeAway: {
    appToken: "8d1cc2ad-e097-4b86-90ef-7a27e19fb833",
    promoId: "dc128d28-c45b-411c-98ff-ac7726fbaea4",
    eventsDelay: 20000, // Set the EVENTS_DELAY for MergeAway
  },
  TwerkRace: {
    appToken: "61308365-9d16-4040-8bb0-2f4a4c69074c",
    promoId: "61308365-9d16-4040-8bb0-2f4a4c69074c",
    eventsDelay: 21000, // Set the EVENTS_DELAY for TwerkRace
  },
};


const generateKeyProcess = async () => {
  const clientId = generateClientId();
  let clientToken;
  try {
    clientToken = await login(clientId);
  } catch (error) {
    alert(`Failed to log in: ${error.message}`);
    startBtn.disabled = false;
    return null;
  }

  const eventsDelay = currentAppConfig.eventsDelay;

  for (let i = 0; i < 10; i++) {
    await sleep(eventsDelay * delayRandom()); // Use the specific eventsDelay
    const hasCode = await emulateProgress(clientToken);
    updateProgress(10 / keyCount);
    if (hasCode) {
      break;
    }
  }

  try {
    const key = await generateKey(clientToken);
    return key;
  } catch (error) {
    alert(
      `Failed to generate key: ${error.message}`
    );
    return null;
  }
};
```

**Comment by Kovirum** [comment]
> ```
> 
> const gamePromoConfigs = {
>   MyCloneArmy: {
>     appToken: "74ee0b5b-775e-4bee-974f-63e7f4d5bacb",
>     promoId: "fe693b26-b342-4159-8808-15e3ff7f8767",
>     eventsDelay: 70000, // Set the EVENTS_DELAY for MyCloneArmy
>   },
>   ChainCube2048: {
>     appToken: "d1690a07-3780-4068-810f-9b5bbf2931b2",
>     promoId: "b4170868-cef0-424f-8eb9-be0622e8e8e3",
>     eventsDelay: 25000, // Set the EVENTS_DELAY for ChainCube2048
>   },
>   TrainMiner: {
>     appToken: "82647f43-3f87-402d-88dd-09a90025313f",
>     promoId: "c4480ac7-e178-4973-8061-9ed5b2e17954",
>     eventsDelay: 18000, // Set the EVENTS_DELAY for TrainMiner
>   },
>   BikeRide3D: {
>     appToken: "d28721be-fd2d-4b45-869e-9f253b554e50",
>     promoId: "43e35910-c168-4634-ad4f-52fd764a843f",
>     eventsDelay: 22000, // Set the EVENTS_DELAY for BikeRide3D
>   },
>   MergeAway: {
>     appToken: "8d1cc2ad-e097-4b86-90ef-7a27e19fb833",
>     promoId: "dc128d28-c45b-411c-98ff-ac7726fbaea4",
>     eventsDelay: 20000, // Set the EVENTS_DELAY for MergeAway
>   },
>   TwerkRace: {
>     appToken: "61308365-9d16-4040-8bb0-2f4a4c69074c",
>     promoId: "61308365-9d16-4040-8bb0-2f4a4c69074c",
>     eventsDelay: 21000, // Set the EVENTS_DELAY for TwerkRace
>   },
> };
> 
> 
> const generateKeyProcess = async () => {
>   const clientId = generateClientId();
>   let clientToken;
>   try {
>     clientToken = await login(clientId);
>   } catch (error) {
>     alert(`Failed to log in: ${error.message}`);
>     startBtn.disabled = false;
>     return null;
>   }
> 
>   const eventsDelay = currentAppConfig.eventsDelay;
> 
>   for (let i = 0; i < 10; i++) {
>     await sleep(eventsDelay * delayRandom()); // Use the specific eventsDelay
>     const hasCode = await emulateProgress(clientToken);
>     updateProgress(10 / keyCount);
>     if (hasCode) {
>       break;
>     }
>   }
> 
>   try {
>     const key = await generateKey(clientToken);
>     return key;
>   } catch (error) {
>     alert(
>       `Failed to generate key: ${error.message}`
>     );
>     return null;
>   }
> };
> ```

But is it necessary to increase the delay in other games, in particular for example ChainCube2048? As far as I have seen, there is no such error and the generation works correctly.

**Comment by Kovirum** [comment]
and yet: I'm not exactly sure yet, but setting the delay to for example 70000 leads to a large number of errors (as above) and as a result, the generation time may be even longer than at 120000.

**Comment by Kovirum** [comment]
Also, I'm not exactly sure yet, but setting the delay, for example, to 70000 leads to a large number of errors (as mentioned above), and as a result, the generation time may be even longer than at 120000.

**Comment by EVMlord** [comment]
> > ```
> > 
> > const gamePromoConfigs = {
> >   MyCloneArmy: {
> >     appToken: "74ee0b5b-775e-4bee-974f-63e7f4d5bacb",
> >     promoId: "fe693b26-b342-4159-8808-15e3ff7f8767",
> >     eventsDelay: 70000, // Set the EVENTS_DELAY for MyCloneArmy
> >   },
> >   ChainCube2048: {
> >     appToken: "d1690a07-3780-4068-810f-9b5bbf2931b2",
> >     promoId: "b4170868-cef0-424f-8eb9-be0622e8e8e3",
> >     eventsDelay: 25000, // Set the EVENTS_DELAY for ChainCube2048
> >   },
> >   TrainMiner: {
> >     appToken: "82647f43-3f87-402d-88dd-09a90025313f",
> >     promoId: "c4480ac7-e178-4973-8061-9ed5b2e17954",
> >     eventsDelay: 18000, // Set the EVENTS_DELAY for TrainMiner
> >   },
> >   BikeRide3D: {
> >     appToken: "d28721be-fd2d-4b45-869e-9f253b554e50",
> >     promoId: "43e35910-c168-4634-ad4f-52fd764a843f",
> >     eventsDelay: 22000, // Set the EVENTS_DELAY for BikeRide3D
> >   },
> >   MergeAway: {
> >     appToken: "8d1cc2ad-e097-4b86-90ef-7a27e19fb833",
> >     promoId: "dc128d28-c45b-411c-98ff-ac7726fbaea4",
> >     eventsDelay: 20000, // Set the EVENTS_DELAY for MergeAway
> >   },
> >   TwerkRace: {
> >     appToken: "61308365-9d16-4040-8bb0-2f4a4c69074c",
> >     promoId: "61308365-9d16-4040-8bb0-2f4a4c69074c",
> >     eventsDelay: 21000, // Set the EVENTS_DELAY for TwerkRace
> >   },
> > };
> > 
> > 
> > const generateKeyProcess = async () => {
> >   const clientId = generateClientId();
> >   let clientToken;
> >   try {
> >     clientToken = await login(clientId);
> >   } catch (error) {
> >     alert(`Failed to log in: ${error.message}`);
> >     startBtn.disabled = false;
> >     return null;
> >   }
> > 
> >   const eventsDelay = currentAppConfig.eventsDelay;
> > 
> >   for (let i = 0; i < 10; i++) {
> >     await sleep(eventsDelay * delayRandom()); // Use the specific eventsDelay
> >     const hasCode = await emulateProgress(clientToken);
> >     updateProgress(10 / keyCount);
> >     if (hasCode) {
> >       break;
> >     }
> >   }
> > 
> >   try {
> >     const key = await generateKey(clientToken);
> >     return key;
> >   } catch (error) {
> >     alert(
> >       `Failed to generate key: ${error.message}`
> >     );
> >     return null;
> >   }
> > };
> > ```
> 
> But is it necessary to increase the delay in other games, in particular for example ChainCube2048? As far as I have seen, there is no such error and the generation works correctly.

Events delay for other games can remain unchanged! The major challenge is in figuring out the optimal time for CloneArmy

**Comment by Kovirum** [comment]
Understood. Then I'll set a delay of 70000 for now so that the generator starts working and issues keys and run some more tests, because it doesn't seem to me to be the best value.

In general, the minimum delay with which the key will be received is 65,000. The question is whether generation with such a delay is the fastest possible. Now I am checking several values - 65000, 70000, 110000, 120000. A lower delay, although it reduces the time between requests, leads to an increase in the number of errors, each of which, in my opinion, increases the generation time.

**Comment by Kovirum** [comment]
So, I did another test and the results on the generation speed with different delays are as follows: (from the fastest to the longest):
1. `120000`
2. `65000`
3. `110000`
4. `70000`

At the same time, for example, the difference between 1 and 2 in time was very large, then not so much, but also noticeable. these tests are very rough, but in general they always show the same result. if someone has the opportunity to conduct their own tests and share the result here, I will be grateful to you. for now, I will leave `70000` on the site and leave this issue open for your comments. I'll check it again tomorrow and maybe change it to `120000`

**Comment by Kovirum** [comment]
The delay value was still changed to `120000`, because complaints from users about the non-working generator continued to arrive + the generation rate with a delay of `120000` is still higher. I think the problem can be considered solved for now (until the developers decide to stop us again)
