### ISSUE TITLE
What would happen if I generate more than 12 keys at once?

### ISSUE THREAD

**Issue by ilshm** [Kovirum/hamster_kombat_bike_keygen_web#18]
Hi! I'm working on a bot that generates activation keys for my accounts. I need to generate 35+ keys every 30 minutes for all my accounts. Will that work, or is there a specific daily limit per IP? Also, why is the maximum set to exactly 12?

**Comment by Kovirum** [comment]
The number 12 is actually chosen randomly, it is not the maximum possible. The API used to generate keys actually has limitations on the number of keys generated, but this value, according to my observations, is not static and depends on the nature of key generation. In general, I can say this: generating more than 20 keys at a time can lead to an error, after which you will have to wait about 5-10 minutes. If you will generate several keys with small time intervals, then most likely there will be no problems. In this case, you will have to experiment and look for a way to achieve maximum performance and not fall within the limits.

**Comment by MohammadHk8** [comment]
I actually tested this and the maximum amount per ip is 24 ( two sets of 12 ) and its pretty reasonable.

**Comment by Kovirum** [comment]
perhaps the developers changed these limits a little, because when I checked it, the second generation of 12 was no longer working (There is even an issue somewhere below about this). therefore, I recommend that you check for yourself how many codes you can generate without problems in how long.

**Comment by Kovirum** [comment]
When generating keys for which game does this error occur? It is usually associated with a too small `eventsDelay' value. I remember that in some games there was this error, but it did not lead to a generation error. Although in this case, increasing the delay for this game may even speed up the generation.
