### ISSUE TITLE
Hamster Kombat (2 more keys are added)

### ISSUE THREAD

**Issue by themrsami** [Kovirum/hamster_kombat_bike_keygen_web#28]
1. Among Water
2. Infected Frontier

**Comment by themrsami** [comment]
15: {
        'name': 'Infected Frontier',
        'appToken': 'eb518c4b-e448-4065-9d33-06f3039f0fcb',
        'promoId': 'eb518c4b-e448-4065-9d33-06f3039f0fcb',
        'timing': 30000 / 1000,
        'attempts': 20,
    },

**Comment by Kovirum** [comment]
Done

**Comment by themrsami** [comment]
1 more key is added (Factory World).
