### ISSUE TITLE
1 more key is added (Factory World).

### ISSUE THREAD

**Issue by themrsami** [Kovirum/hamster_kombat_bike_keygen_web#29]
1 more key is added (Factory World).

_Originally posted by @themrsami in https://github.com/Kovirum/hamster_kombat_bike_keygen_web/issues/28#issuecomment-2361143413_

**Comment by themrsami** [comment]
17: {
        'name': 'Factory World',
        'appToken': 'd02fc404-8985-4305-87d8-32bd4e66bb16',
        'promoId': 'd02fc404-8985-4305-87d8-32bd4e66bb16',
        'timing': 30000 / 1000,
        'attempts': 20,
    },

**Comment by Kovirum** [comment]
Done
