### ISSUE TITLE
Failed to Login

### ISSUE THREAD

**Issue by Adeboy901** [Kovirum/hamster_kombat_bike_keygen_web#3]
Getting the failed to login error
![Uploading Screenshot_20240806_114413_Chrome.jpg…]()

**Comment by Kovirum** [comment]
Your attachment is not working, so I can't see the situation exactly. Is this an error provided in my ![attachment](https://github.com/user-attachments/assets/a48b69ca-6f51-4df1-a5c5-53b87174b17a)? Does it affect the key generation process (it freezes/ the key is empty, etc.) If so, under what circumstances does this error appear (on the kovirum.github.io/on a local server/on localhost/on another external server).

At the moment, this error may appear in the console during generation, but it does not affect the issuance of codes in any way. If this is the case, then for now I can only suggest not to pay attention to it. A small update was released that disabled the user's notification of a login error, so if the generation is working correctly, then everything is fine.

**Comment by MohammadHk8** [comment]
I'm having the same error , not only with your project but also with other similar projects. doesn't matter local or not local.
it happens after the first batch of codes.
here is the error : 
![image](https://github.com/user-attachments/assets/51f1f09a-fa01-4683-bdfe-87e7e8631232)

**Comment by Kovirum** [comment]
The error analysis resulted in the following: The error appears after generating 20 keys in a short period of time.  The server response contains the following information: {error_code: 'Too Many Ip Request', error_message: 'Too many login attempts from single ip'}. I.e., this is a certain rate limit linked to IP.  20 requests once at a certain time (my test showed 10 minutes, but maybe this value is dynamic). So far, I can only advise you not to generate too many keys at a time, or use a proxy

**Comment by MohammadHk8** [comment]
> The error analysis resulted in the following: The error appears after generating 20 keys in a short period of time. The server response contains the following information: {error_code: 'Too Many Ip Request', error_message: 'Too many login attempts from single ip'}. I.e., this is a certain rate limit linked to IP. 20 requests once at a certain time (my test showed 10 minutes, but maybe this value is dynamic). So far, I can only advise you not to generate too many keys at a time, or use a proxy
Ok thank you <3
