### ISSUE TITLE
Risks

### ISSUE THREAD

**Issue by TaikoGoujo** [Kovirum/hamster_kombat_bike_keygen_web#6]
Is there a risk of banning the account or being detected by Hamster Kombat?

**Comment by Kovirum** [comment]
I can't give any guarantees regarding the safety of using this algorithm, but in fact these keys are generated using the same algorithm as in a regular game. I would recommend generating 1 key every few minutes to further reduce the risks.

**Comment by w00xy** [comment]
https://t.me/hamsterkombate_keys use this and don't get the ban
