### ISSUE TITLE
Code doesn't exist 

### ISSUE THREAD

**Issue by MohammadHk8** [Kovirum/hamster_kombat_bike_keygen_web#9]
Sometimes one of the codes or more just doesn't work.
 it's very rare but can be annoying.

**Comment by Kovirum** [comment]
So, do you mean that the codes are generated correctly, but when you try to use them in the game, you encounter the error "The code does not exist"? To be honest, I have never encountered such a problem, although I use this generator myself. 
How rarely does this happen at all and is it permanent? That is, conditionally, every 100 generations there is a non-working code, or does it happen at random moments?

**Comment by MohammadHk8** [comment]
> So, do you mean that the codes are generated correctly, but when you try to use them in the game, you encounter the error "The code does not exist"? 

**Yes exactly. I think it's random.
I save the generated codes in my saved messages in telegram and use them for days. Maybe there is an expiration date on the codes idk?**

**Comment by Kovirum** [comment]
I haven't noticed that the codes have an expiration date, but maybe they do. How long do you keep these codes? For example, I think my bot already has codes that are 3-4 days old and there have been no complaints that they do not work.

 In fact, there is nothing to be done about it, and even the reason for such an error is unclear

**Comment by Kovirum** [comment]
When my bot was active, some of the codes there had a limitation period of up to a week and seemed to work (I did not receive any complaints about the non-working code). Perhaps the developers have already changed this deadline or something similar. In fact, we can't do anything anyway, so I can only suggest using the new codes.
